swagger: "2.0"
info: 
  title: "Fuel consumption"
  description: "OpenApi specification for Nasa ships fuel consumption"
  version: "1.0.0"
  contact:
    email: "azik1kurbanov@gmail.com"
host: "localhost:4000"
basePath: "/api"
schemes:
- "http"
paths:
  /calculate:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "params"
        required: true
        schema:
          $ref: "#/definitions/FlyingPlan"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Errors"
        "500":
          description: "Internal Server Errror"
          schema:
            $ref: "#/definitions/Errors"
definitions:
  FlyingPlan:
    type: "object"
    properties:
      shipMass:
        type: "integer"
        format: "int64"
        example: 28801
      points:
        type: "array"
        items:
          $ref: "#/definitions/Point"
  Point:
    type: "object"
    properties:
      launch:
        type: "number"
        format: "float"
        example: 9.807
      land:
        type: "number"
        format: "float"
        example: 1.62
  ApiResponse:
    type: "object"
    properties:
      fuelConsumption:
        type: "integer"
        format: "int64"
  Errors:
    type: "object"
    properties:
      errors:
        type: object
        properties:
          detail:
            type: "string"
            example: "Error message"