swagger: "2.0"
info: 
  title: "Fuel consumption"
  description: "OpenApi specification for Nasa ships fuel consumption"
  version: "1.0.0"
  contact:
    email: "azik1kurbanov@gmail.com"
host: "localhost:4000"
basePath: "/api"
schemes:
- "http"
paths:
  /calculate:
    get:
      summary: "Welcome text"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Welcome text"
          schema:
            type: object
            properties:
              title:
                type: string
                example: "Welcome text"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "params"
        required: true
        schema:
          $ref: "#/definitions/FlyingPlan"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Errors"
        "500":
          description: "Internal Server Errror"
          schema:
            $ref: "#/definitions/Errors"
definitions:
  FlyingPlan:
    type: "object"
    properties:
      ship_mass:
        type: "integer"
        format: "int64"
        example: 28801
      points:
        type: "array"
        items:
          $ref: "#/definitions/Point"
    required:
    - "ship_mass"
    - "points"
  Point:
    type: "object"
    properties:
      launch:
        type: "number"
        format: "float"
        example: 9.807
      land:
        type: "number"
        format: "float"
        example: 1.62
    required:
    - "launch"
    - "land"
  ApiResponse:
    type: "object"
    properties:
      fuel_consumption:
        type: "number"
        format: "float"
        example: 36778.0
    required:
    - "fuel_consumption"
  Errors:
    type: "object"
    properties:
      errors:
        type: "object"
        properties:
          detail:
            type: "string"
            example: "Error message"
          source:
            type: "object"
            properties:
              pointer: 
                type: "string"
                example: "/points/0/launch"
          title: 
            type: "string"
            example: "Invalid value"
        required:
        - "detail"